### ISSUE TITLE
《如何在 Weex 中使用 Vue》

### ISSUE THREAD

**Issue by Hanks10100** [weexteam/vue-framework-for-Apache-Weex#16]
## (内容暂时去掉了，敬请期待 [WeexConf](https://atf.alibaba.com/weex) ~)

# How to use Vue in Weex

Weex is an easy-to-use cross-platform development solution that builds high-performance, scalable native applications with a Web development experience. Vue is a lightweight and powerful progressive front-end framework. Weex and Vue have official cooperation, Weex now support Vue 2.x as its built-in front-end framework. We also recommend to use Vue 2.x to develop native applications.

# 如何在 Weex 中使用 Vue

Weex 是一套简单易用的跨平台开发方案，能以 Web 的开发体验构建高性能、可扩展的原生应用。Vue 是一个轻量并且功能强大的渐进式前端框架。Weex 与 Vue 有官方合作，支持将 Vue 2.x 作为 Weex 内置的前端框架，我们也推荐大家使用 Vue 2.x 的语法开发原生应用。

**Comment by OXOYO** [comment]
赞一个先，强强联手啊！

**Comment by itbeihe** [comment]
找了半天  weex-toolkit  0.8.0 和vue-cli 3.0.0。转回来发现没看本文第一句。哭

**Comment by Hanks10100** [comment]
@itbeihe 是我失误，文章抛出来的太早……

**Comment by alwayrun** [comment]
@Hanks10100  现在 Weex 能直接使用 Vue 2.x 了吗?
