### ISSUE TITLE
代码都一年没什么变更了，这个项目是不是死掉了？！

### ISSUE THREAD

**Issue by libbylg** [weexteam/vue-framework-for-Apache-Weex#24]
### Vue.js version
2.0.2

**Comment by Hanks10100** [comment]
目前这个仓库里的代码已经不更新了，最新代码已经转移到 Vue 官方仓库里，位置在 [src/platforms/weex](https://github.com/vuejs/vue/tree/dev/src/platforms/weex) 目录下。Weex 的部分功能也会写在 Vue 主仓库里。
